theme: jekyll-theme-minimal
timezone: Europe/Berlin
future: false # Don't publish articles with a future date
unpublished: false # Don't render unpublished articles, obviously
# Minimal theme specific options
title: Riotblog
description: "Riots as Stasis: This blog contains stories and intermediate results from my PhD on the topic of riots."
show_downloads: false # No download url, b/c there is nothing to download
logo: /assets/naisen.png
# google_analytics: [Your Google Analytics tracking ID]
